src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Symfony\Component\Validator\Constraints as Assert;

use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(unique: true, length: 255)]
    #[Slug(fields: ['name'])]
    #[Groups(['group1'])]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    #[Groups(['group1'])]
    private ?string $name = null;

    #[ORM\Column(length: 1024, nullable: true)]
    #[Groups(['group1'])]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'Projects')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creationTime = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updateTime = null;

    #[ORM\OneToMany(mappedBy: 'Project', targetEntity: Critery::class, orphanRemoval: true)]
    #[Groups(['group1'])]
    private Collection $Critery;

    #[ORM\OneToMany(mappedBy: 'Project', targetEntity: Variant::class, orphanRemoval: true)]
    #[Groups(['group1'])]
    private Collection $Variant;

    #[ORM\OneToMany(mappedBy: 'Project', targetEntity: Klas::class, orphanRemoval: true)]
    #[Groups(['group1'])]
    private Collection $Klas;

    #[ORM\OneToMany(mappedBy: 'Project', targetEntity: Profil::class, orphanRemoval: true)]
    #[Groups(['group1'])]
    private Collection $Profil;

    #[ORM\Column(nullable: true)]
    #[Assert\GreaterThan(0.5)]
    #[Assert\LessThanOrEqual(1)]
    #[Groups(['group1'])]
    private ?float $CutOffLevel = null;

    public function __construct()
    {
        $this->Critery = new ArrayCollection();
        $this->Variant = new ArrayCollection();
        $this->Klas = new ArrayCollection();
        $this->Profil = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): void
    {
        $this->slug = $slug;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreationTime(): ?\DateTimeInterface
    {
        return $this->creationTime;
    }

    public function setCreationTime(\DateTimeInterface $creationTime): self
    {
        $this->creationTime = $creationTime;

        return $this;
    }

    public function getUpdateTime(): ?\DateTimeInterface
    {
        return $this->updateTime;
    }

    public function setUpdateTime(\DateTimeInterface $updateTime): self
    {
        $this->updateTime = $updateTime;

        return $this;
    }

    /**
     * @return Collection<int, Critery>
     */
    public function getCritery(): Collection
    {
        return $this->Critery;
    }

    public function addCritery(Critery $critery): self
    {
        if (!$this->Critery->contains($critery)) {
            $this->Critery->add($critery);
            $critery->setProject($this);
        }

        return $this;
    }

    public function removeCritery(Critery $critery): self
    {
        if ($this->Critery->removeElement($critery)) {
            // set the owning side to null (unless already changed)
            if ($critery->getProject() === $this) {
                $critery->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Variant>
     */
    public function getVariant(): Collection
    {
        return $this->Variant;
    }

    public function addVariant(Variant $variant): self
    {
        if (!$this->Variant->contains($variant)) {
            $this->Variant->add($variant);
            $variant->setProject($this);
        }

        return $this;
    }

    public function removeVariant(Variant $variant): self
    {
        if ($this->Variant->removeElement($variant)) {
            // set the owning side to null (unless already changed)
            if ($variant->getProject() === $this) {
                $variant->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Klas>
     */
    public function getKlas(): Collection
    {
        return $this->Klas;
    }

    public function addKlas(Klas $klas): self
    {
        if (!$this->Klas->contains($klas)) {
            $this->Klas->add($klas);
            $klas->setProject($this);
        }

        return $this;
    }

    public function removeKlas(Klas $klas): self
    {
        if ($this->Klas->removeElement($klas)) {
            // set the owning side to null (unless already changed)
            if ($klas->getProject() === $this) {
                $klas->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Profil>
     */
    public function getProfil(): Collection
    {
        return $this->Profil;
    }

    public function addProfil(Profil $profil): self
    {
        if (!$this->Profil->contains($profil)) {
            $this->Profil->add($profil);
            $profil->setProject($this);
        }

        return $this;
    }

    public function removeProfil(Profil $profil): self
    {
        if ($this->Profil->removeElement($profil)) {
            // set the owning side to null (unless already changed)
            if ($profil->getProject() === $this) {
                $profil->setProject(null);
            }
        }

        return $this;
    }

    public function getCutOffLevel(): ?float
    {
        return $this->CutOffLevel;
    }

    public function setCutOffLevel(float $CutOffLevel): self
    {
        $this->CutOffLevel = $CutOffLevel;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Wernyhora{% endblock %}</title>
{#        <link rel="icon" type="image/svg+xml" href="{{ asset('build/images/remove_red_eye_black.svg') }}">#}
{#        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">#}
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,700,0,0" />
        {% endblock %}

        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
            {{ encore_entry_script_tags('app') }}
            {{ encore_entry_script_tags('app_collection') }}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        {% endblock %}

        {% for message in app.flashes('success') %}
            <div  style="background-color: #0d6efd; margin-bottom: 0px;">
                <div class="container alert alert-success col-4 text-center" style="margin-bottom: 0px;">
                    <h2>{{ message }}</h2>
                </div>
            </div>

        {% endfor %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

templates/top_menu.html.twig
{% if app.user %}
    <div style="background-color: #0d6efd;">
        <div class="d-flex container pt-1">
            <div class="col-6 justify-content-start m">
                <h2><a href="{{ path('app_manage_projects') }}" style="text-decoration: none; color: #FFFFFF;">WERNYHORA</a></h2>
            </div>
            <div class="dropdown col-6 mb-3 text-end mr-1">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="material-symbols-outlined">menu</span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1" style="background-color: #0d6efd;">
                    <li><a class="dropdown-item" href="/projects" style="color: #FFFFFF;">
                            <div class="d-flex flex-row">
                                <div style="padding-right: 2px;">
                                    <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">person</span>
                                </div>
                                <div>
                                    <span class="text-center">{{ app.user.getEmail }}</span>
                                </div>
                            </div>
                            </a></li>
                    <li><a class="dropdown-item" href="{{ path('app_logout') }}" style="color: #FFFFFF;">
                            <div class="d-flex flex-row">
                                <div style="padding-right: 2px;">
                                    <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">logout</span>
                                </div>
                                <div>
                                    <span class="text-center">Wyloguj</span>
                                </div>
                            </div>

                        </a></li>

                    {% if project is defined %}
                        <li><a class="dropdown-item" href="/projects/edit/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                <div class="d-flex flex-row">
                                    <div style="padding-right: 2px;">
                                        <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">emoji_objects</span>
                                    </div>
                                    <div>
                                        <span class="text-center">Projekt</span>
                                    </div>
                                </div>
                            </a></li>
                        <li><a class="dropdown-item" href="/projects/edit/critery/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                <div class="d-flex flex-row">
                                    <div style="padding-right: 2px;">
                                        <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">sort</span>
                                    </div>
                                    <div>
                                        <span class="text-center">Kryteria</span>
                                    </div>
                                </div>
                            </a></li>
                        <li><a class="dropdown-item" href="/projects/edit/variant/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                <div class="d-flex flex-row">
                                    <div style="padding-right: 2px;">
                                        <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">keyboard_option_key</span>
                                    </div>
                                    <div>
                                        <span class="text-center">Warianty</span>
                                    </div>
                                </div>
                            </a></li>
                        {% if project.critery|length and project.variant|length %}
                            <li><a class="dropdown-item" href="/projects/edit/variants_values/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                    <div class="d-flex flex-row">
                                        <div style="padding-right: 2px;">
                                            <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">123</span>
                                        </div>
                                        <div>
                                            <span class="text-center">Wartości wariantów</span>
                                        </div>
                                    </div>
                                </a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="/projects/edit/klas/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                <div class="d-flex flex-row">
                                    <div style="padding-right: 2px;">
                                        <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">category</span>
                                    </div>
                                    <div>
                                        <span class="text-center">Klasy</span>
                                    </div>
                                </div>
                            </a></li>
                        {% if project.klas|length %}
                            <li><a class="dropdown-item" href="/projects/edit/profils_values/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                    <div class="d-flex flex-row">
                                        <div style="padding-right: 2px;">
                                            <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">filter_alt</span>
                                        </div>
                                        <div>
                                            <span class="text-center">Profile</span>
                                        </div>
                                    </div>
                                </a></li>
                        {% endif %}
                        {% if project.critery|length %}
                            <li><a class="dropdown-item" href="/projects/edit/threshold_values/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                    <div class="d-flex flex-row">
                                        <div style="padding-right: 2px;">
                                            <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">tune</span>
                                        </div>
                                        <div>
                                            <span class="text-center">Progi</span>
                                        </div>
                                    </div>
                                </a></li>
                        {% endif %}
                        {% if
                            project.critery|length and project.critery[0].VariantValue|length
                            and project.critery[0].alfaQ and project.critery[0].betaQ
                            and project.critery[0].alfaP and project.critery[0].betaP
                            and project.critery[0].alfaV and project.critery[0].betaV
                            and project.variant|length and project.klas|length
                            and project.profil|length and project.profil[0].profilValue|length %}
                            <li><a class="dropdown-item" href="/projects/raport/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                    <div class="d-flex flex-row">
                                        <div style="padding-right: 2px;">
                                            <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">quick_reference_all</span>
                                        </div>
                                        <div>
                                            <span class="text-center">Raport</span>
                                        </div>
                                    </div>
                                </a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="/projects/export/{{ project.slug }}" class="text-white text-decoration-none" style="color: #FFFFFF;">
                                <div class="d-flex flex-row">
                                    <div style="padding-right: 2px;">
                                        <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">call_made</span>
                                    </div>
                                    <div>
                                        <span class="text-center">Eksport</span>
                                    </div>
                                </div>
                            </a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="/projects/import" class="text-white text-decoration-none" style="color: #FFFFFF;">
                            <div class="d-flex flex-row">
                                <div style="padding-right: 2px;">
                                    <span class="material-symbols-outlined material-symbols-outlined-menu" style="color: #FFFFFF;">call_received</span>
                                </div>
                                <div>
                                    <span class="text-center">Import</span>
                                </div>
                            </div>
                        </a></li>
                </ul>
            </div>
        </div>
    </div>

{% endif %}